Task - 1
Write a program that allows you to enter 4 numbers
and stores them in a file called “Numbers”
• 3
• 45
• 83
• 21
Have a go at ‘w’ ‘r’ ‘a’

In [27]:
#Write into a file
print("Writing 3, 45, 83 and 21 into a file")
file1 =  open("Numbers.txt", 'w')
for i in range(0,4):
    n = input("Choose a number: ")
    file1.write(n)
    file1.write("\n")

file1.close()

#Read from a file
print("Reading from a file")
with open("Numbers.txt", 'r') as file2:
    print(file2.read())
file2.close()

#Append to a file
print("Now appending '100' to a file")
with open("Numbers.txt", 'a') as file3:
    file3.write("100")
file3.close()
#Read after appending
print("Reading after append")
with open("Numbers.txt", 'r') as f:
    print(f.read())


Writing 3, 45, 83 and 21 into a file
Reading from a file
3
45
83
21

Now appending '100' to a file
Reading after append
3
45
83
21
100


Task - 2
Write a program to ask a student for their percentage mark and
convert this to a grade.

Extension:
• Ask the user for their target grade and print this with their
mark
• If their target grade > exam grade display a suitable
message
• If their target grade = exam grade display a suitable
message
• If their target grade < exam grade display a suitable
message

In [70]:
#Task - 2

def mark_grade(perct_mark):
    if perct_mark == 100 or perct_mark == 99:
        print("Your grade is 9")
        return '9'
    elif perct_mark >= 94 and perct_mark <= 98:
        print("Your grade is 8")
        return '8'  
    elif perct_mark >= 89 and perct_mark <= 93:
        print("Your grade is 7")
        return '7'
    elif perct_mark >= 78 and perct_mark <= 88:
        print("Your grade is 6")
        return '6'
    elif perct_mark >= 67 and perct_mark <= 77:
        print("Your grade is 5")
        return '5'
    elif perct_mark >= 56 and perct_mark <= 66:
        print("Your grade is 4")
        return '4'
    elif perct_mark >= 41 and perct_mark <= 55:
        print("Your grade is 3")
        return '3'
    elif perct_mark >= 26 and perct_mark <= 40:
        print("Your grade is 2")
        return '2'
    elif perct_mark >= 11 and perct_mark <= 25:
        print("Your grade is 1")
        return '1'
    elif perct_mark > 0 and perct_mark < 10:
        print("Your grade is U")
        return 'U'
    else:
        print("Percentage marks not in range.")
        return None
    

mark = int(input("Enter your percentage mark:"))
exam_grade = mark_grade(mark)

#Extension:
target_grade = input("Enter your target grade:")

if target_grade > exam_grade:
    print("Your exam grade is below target.")
elif target_grade == exam_grade:
    print("Well done! You achieved your target grade.")
elif target_grade < exam_grade:
    print("Excellent! Your exam grade is above target.")




Your grade is 8
Your exam grade is below target.


Task - 3

Create a 1D array of numbers from 0 to 9

In [75]:
#Task - 3

#python3 -m pip install numpy

import numpy as np

array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print("1D array of numbers: ", array)
#print(np.__version__)

1D array of numbers:  [0 1 2 3 4 5 6 7 8 9]


Task - 4

Create a 3×3 NumPy array of all Boolean value Trues

In [109]:
#Task - 4
import numpy as np

arr = np.ones(9, dtype='bool')
new_arr = arr.reshape(3,3)

#print(arr)
print("3×3 NumPy array of all Boolean value Trues is:")
print(new_arr)


3×3 NumPy array of all Boolean value Trues is:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Task - 5

Extract all odd numbers from array of 1-10

Task - 6

Replace all odd numbers in an array of 1-10 with the value -1

In [122]:
#Task - 5 and 6
import numpy as np

array = np.arange(1,11)

print(array)
print("All odd numbers from array of 1-10 is", array[0:10:2])

arr_odd = array[0:10:2]
print("Replacing all odd numbers in an array of 1-10 with the value -1: ",np.where(arr_odd > 0, -1, arr_odd))


[ 1  2  3  4  5  6  7  8  9 10]
All odd numbers from array of 1-10 is [1 3 5 7 9]
Replacing all odd numbers in an array of 1-10 with the value -1:  [-1 -1 -1 -1 -1]


Task - 7

Convert a 1D array to a 2D array with 2 rows

In [131]:
#Task - 7
import numpy as np

array = np.arange(1,11)

print("1D Array of numbers:", array)

print("Convert a 1D array to a 2D array with 2 rows:\n", array.reshape(2,5))

1D Array of numbers: [ 1  2  3  4  5  6  7  8  9 10]
Convert a 1D array to a 2D array with 2 rows:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Task - 8

Create two arrays a and b, stack these two arrays vertically use the np.dot and
np.sum to calculate totals

In [207]:
#Task - 8

import numpy as np

"""
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)
print("Array 1:\n", a)
print("Array 2:\n", b)

c = np.dot(a, b)
e = np.sum(c, axis = 1, keepdims=True)

print("Product of array 1 and 2:\n", c)
print("Sum with axis = 1:\n", e)
"""

a = np.array([[1, 2], [3, 4]])
b = np.array([[4, 5], [6, 7]])
print("Array 1:\n", a)
print("Array 2:\n", b)


#Vertical stack
#s1 = np.vstack(a)
#s2 = np.vstack(b)

c = np.vstack((a,b))
print("Stacking two arrays a and b vertically:\n", c)

product= np.dot(a,b)
total = np.sum(product)
print("Product of arrays a and b:\n", product)
print("Totals: ", total)


Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[4 5]
 [6 7]]
Stacking two arrays a and b vertically:
 [[1 2]
 [3 4]
 [4 5]
 [6 7]]
Product of arrays a and b:
 [[16 19]
 [36 43]]
Totals:  114


Extension:

1. Create the following pattern without hardcoding. Use only NumPy functions.
2. In two arrays a (1,2,3,4,5) and b (4,5,6,7,8,9) – remove all repeating items 
    present in array b
3. Get all items between 3 and 7 from a and b and sum them together

In [215]:
# 1.Pattern 

import numpy as np

a = np.array([1,2,3])
x = np.repeat(a, 3)
y = np.tile(a, 3)

print(x)
print(y)
array = np.concatenate((x,y))
print("Pattern Array:", array)

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
Pattern Array: [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [228]:
# 2. Remove repeat present in array b
import numpy as np

a = np.array([1,2,3,4])
b = np.array([4,5,6,7,8,9])
copy = b
c = np.setdiff1d(b, a)
b = c
print("Removed repeat present in array b::", c)

Removed repeat present in array b:: [5 6 7 8 9]


In [240]:
# 3. Get all items between 3 and 7 and then sum

import numpy as np

a = np.array([1,2,3,4])
b = np.array([4,5,6,7,8,9])
c = np.concatenate((a,b))
print(c)

items = c[2:8]
print("All items between 3 and 7 from a and b are: ", items)
print("Summed together: ",np.sum(items))

[1 2 3 4 4 5 6 7 8 9]
All items between 3 and 7 from a and b are:  [3 4 4 5 6 7]
Summed together:  29
